### ISSUE TITLE
How to for singularity noob

### ISSUE THREAD

**Issue by underOATH777** [ResearchIT/eman2#1]
Hi, our server runs Ubuntu, could you please give some noob instructions on how to build a singulairty of Eman2 using your repo?

**Comment by snehring** [comment]
a guide for singularity can be found at https://sylabs.io/guides/3.6/user-guide/
This is a definition file so you just need to build the image as demonstrated under https://sylabs.io/guides/3.6/user-guide/quick_start.html#singularity-definition-files

**Comment by underOATH777** [comment]
Thanks, however upon launching I got the following:

FATAL:   container creation failed: mount /proc/self/fd/3->/usr/local/var/singularity/mnt/session/rootfs error: can't mount image /proc/self/fd/3: failed to mount squashfs filesystem: invalid argument

I have singularity version 3.3.0

**Comment by snehring** [comment]
I'd suggest you make sure you have squashfs installed through your package manager, but beyond that I can't provide support for the myriad of possible configurations. You'll probably want to reach out to the singularity community or your distro's community.
